# Generated by Django 3.1.4 on 2020-12-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huey_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Last Signal information', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='huey_monitor.signalinfomodel', verbose_name='State'),
        ),
    ]
