# Generated by Django 3.1.4 on 2020-12-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huey_monitor', '0002_fix_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalinfomodel',
            name='hostname',
            field=models.CharField(default='unknown', help_text='Hostname of the machine that creates this Signal', max_length=128, verbose_name='Hostname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signalinfomodel',
            name='pid',
            field=models.PositiveIntegerField(default=9999, help_text='Process ID that creates this Signal', verbose_name='PID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signalinfomodel',
            name='thread',
            field=models.CharField(default='unknown', help_text='Name of the thread that creates this Signal', max_length=128, verbose_name='Thread Name'),
            preserve_default=False,
        ),
    ]
