# Generated by Django 3.2.12 on 2022-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huey_monitor', '0005_progress_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='desc',
            field=models.CharField(blank=True, default='', help_text='Prefix for progress information', max_length=64, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='finished',
            field=models.BooleanField(default=False, help_text='Indicates that this Task no longer waits or run. (It does not mean that execution was successfully completed.)', verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='progress_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of units processed (If provided)', null=True, verbose_name='Progress Count'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='cumulate_progress',
            field=models.BooleanField(default=True, help_text='Should the progress of the sub tasks be added up and saved in the parent task? (Will be done after the task has ended)', verbose_name='Cumulate Progress?'),
        ),
        migrations.AddField(
            model_name='signalinfomodel',
            name='progress_count',
            field=models.PositiveIntegerField(blank=True, help_text='Progress (if any) at the time of creation.', null=True, verbose_name='Progress Count'),
        ),
    ]
