# Generated by Django 3.2.12 on 2022-02-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huey_monitor', '0007_data_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskProgressModel',
        ),
    ]
