# Generated by Django 3.2.12 on 2022-02-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huey_monitor', '0008_delete_taskprogressmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalinfomodel',
            name='exception_line',
            field=models.TextField(blank=True, max_length=128, verbose_name='Exception Line'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='desc',
            field=models.CharField(blank=True, default='', help_text='Prefix for progress information', max_length=128, verbose_name='Description'),
        ),
    ]
