# Generated by Django 3.2.14 on 2022-11-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('huey_monitor', '0009_fix_optinal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='parent_task',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text='Only set if this task is a sub task started from his parent.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sub_tasks',
                to='huey_monitor.taskmodel',
                verbose_name='Parent Task',
            ),
        ),
    ]
